### ISSUE TITLE
Fix git commands 

### ISSUE THREAD

**Issue by mujtaba1747** [mujtaba1747/git-autocommit#3]
Order of git commands is a bit wrong and requires improvement.

**Comment by pratikdaigavane** [comment]
@mujtaba1747 should i work on this?

**Comment by mujtaba1747** [comment]
> @mujtaba1747 should i work on this?
@pratikdaigavane , Sure !!

**Comment by mujtaba1747** [comment]
Thanks a lot @pratikdaigavane !
